[build]
  publish = "./"                    # Ensure the path points to the correct folder
  functions = "netlify/functions"  # Verify this folder exists in your project

[functions]
  node_bundler = "esbuild"         # Ensure esbuild is installed and configured

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true